name: Backpack
main: main.Main
version: 1.0
commands:
  test:
  gui:

permissions:
  gui.1:
    default: true
    description: test
  gui.2:
    description: test
  gui.3:
    description: test
  gui.4:
    description: test